version: '3.1'

services:
  multimedia-author:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456@Dev
      MYSQL_DATABASE: author
    ports:
      - "3308:3306"

  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
